---
title: "flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
## Loading required package: viridisLite
library(p8105.datasets)
library(plotly)
```

```{r}
set.seed(1)

insta_df = p8105.datasets::instacart %>% 
  janitor::clean_names()

noaa_df = p8105.datasets::ny_noaa %>% 
  janitor::clean_names() %>% 
  mutate(prcp = as.numeric(prcp)/10, tmax = as.numeric(tmax)/10, tmin = as.numeric(tmin)/10) %>% # change the unit
  rename(prcp_in_mm = prcp, snow_in_mm = snow, snwd_in_mm = snwd, tmax_in_celsius = tmax, tmin_in_celsius = tmin)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
noaa_df %>% 
  filter(tmin_in_celsius != "NA") %>% 
  filter(tmax_in_celsius != "NA") %>%
  group_by(id) %>% 
  summarise(mean_tmin = mean(tmin_in_celsius), 
            mean_tmax = mean(tmax_in_celsius), 
            mean_prcp = mean(prcp_in_mm, na.rm = T)) %>%
  plot_ly(x = ~mean_tmin, y = ~mean_tmax, type = "scatter", mode = "markers", 
          alpha = 0.5, 
          text = ~id, 
          color = ~mean_prcp) %>% 
  layout(
    title = "stations and their mean tmin and mean tmax from 1981 to 2010", 
    xaxis = list(title = "mean tmin (Celsius)"), 
    yaxis = list(title = "mean tmax (Celsius)")
    )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
insta_df %>% 
  count(department) %>%
  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar") %>% 
  layout(
    title = "total number of items ordered in each department", 
    yaxis = list(title = "# of items ordered")
  )
```

### Chart C

```{r}
noaa_df %>% 
  filter(tmax_in_celsius != "NA") %>%
  separate(date, into = c("year", "month", "day"), sep = "-") %>% # separate the date
  plot_ly(x = ~year, y = ~tmax_in_celsius, type = "box", color = ~year) %>% 
  layout(
    yaxis = list(title = "max temperature (Celsius)"), 
    title = "max temperature across years"
  )
```

